### ISSUE TITLE
Platform error Error R14 (Memory quota exceeded)

### ISSUE THREAD

**Issue by samyun** [samyun/southwest-price-drop-bot#6]

**Comment by rusd1123** [comment]
Deployed the latest build that closed this bug, but this afternoon it looks like I am seeing the same error.

```
Apr 29 09:29:35 appname heroku/scheduler.6167: Starting process with command `npm run task:check` 
Apr 29 09:29:36 appname heroku/scheduler.6167: State changed from starting to up 
Apr 29 09:29:38 appname app/scheduler.6167: > southwest-price-drop-bot@3.0.1 task:check /app 
Apr 29 09:29:38 appname app/scheduler.6167: > node --trace-warnings tasks/check.js 
Apr 29 09:29:39 appname app/scheduler.6167: checking 13 flights 
Apr 29 09:29:41 appname app/scheduler.6167: (node:20) UnhandledPromiseRejectionWarning: Error: Page crashed! 
Apr 29 09:29:41 appname app/scheduler.6167:     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:118:24) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:104:56) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:219:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:119:19) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at WebSocket.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitWarning (internal/process/promises.js:65:17) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11) 
Apr 29 09:29:41 appname app/scheduler.6167:     at runMicrotasksCallback (internal/process/next_tick.js:124:9) 
Apr 29 09:29:41 appname app/scheduler.6167:     at _combinedTickCallback (internal/process/next_tick.js:131:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at process._tickCallback (internal/process/next_tick.js:180:9) 
Apr 29 09:29:41 appname app/scheduler.6167: (node:20) Error: Page crashed! 
Apr 29 09:29:41 appname app/scheduler.6167:     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:118:24) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:104:56) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:219:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:119:19) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at WebSocket.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167: (node:20) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitWarning (internal/process/promises.js:92:15) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11) 
Apr 29 09:29:41 appname app/scheduler.6167:     at runMicrotasksCallback (internal/process/next_tick.js:124:9) 
Apr 29 09:29:41 appname app/scheduler.6167:     at _combinedTickCallback (internal/process/next_tick.js:131:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at process._tickCallback (internal/process/next_tick.js:180:9) 
Apr 29 09:29:41 appname app/scheduler.6167: (node:20) UnhandledPromiseRejectionWarning: Error: Page crashed! 
Apr 29 09:29:41 appname app/scheduler.6167:     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:118:24) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:104:56) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:219:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:119:19) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at WebSocket.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitWarning (internal/process/promises.js:65:17) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11) 
Apr 29 09:29:41 appname app/scheduler.6167:     at runMicrotasksCallback (internal/process/next_tick.js:124:9) 
Apr 29 09:29:41 appname app/scheduler.6167:     at _combinedTickCallback (internal/process/next_tick.js:131:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at process._tickCallback (internal/process/next_tick.js:180:9) 
Apr 29 09:29:41 appname app/scheduler.6167: (node:20) Error: Page crashed! 
Apr 29 09:29:41 appname app/scheduler.6167:     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:118:24) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:104:56) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:219:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:119:19) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at WebSocket.emit (events.js:211:7) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22) 
Apr 29 09:29:41 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:41 appname app/scheduler.6167:     at Socket.emit (events.js:211:7) 
Apr 29 09:29:42 appname app/scheduler.6167: (node:20) UnhandledPromiseRejectionWarning: Error: Page crashed! 
Apr 29 09:29:42 appname app/scheduler.6167:     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:118:24) 
Apr 29 09:29:42 appname app/scheduler.6167:     at CDPSession.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:104:56) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:42 appname app/scheduler.6167:     at CDPSession.emit (events.js:211:7) 
Apr 29 09:29:42 appname app/scheduler.6167:     at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:219:12) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:119:19) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:42 appname app/scheduler.6167:     at WebSocket.emit (events.js:211:7) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Socket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Socket.emit (events.js:211:7) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitWarning (internal/process/promises.js:65:17) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11) 
Apr 29 09:29:42 appname app/scheduler.6167:     at runMicrotasksCallback (internal/process/next_tick.js:124:9) 
Apr 29 09:29:42 appname app/scheduler.6167:     at _combinedTickCallback (internal/process/next_tick.js:131:7) 
Apr 29 09:29:42 appname app/scheduler.6167:     at process._tickCallback (internal/process/next_tick.js:180:9) 
Apr 29 09:29:42 appname app/scheduler.6167: (node:20) Error: Page crashed! 
Apr 29 09:29:42 appname app/scheduler.6167:     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:118:24) 
Apr 29 09:29:42 appname app/scheduler.6167:     at CDPSession.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:104:56) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:42 appname app/scheduler.6167:     at CDPSession.emit (events.js:211:7) 
Apr 29 09:29:42 appname app/scheduler.6167:     at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:219:12) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:119:19) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:42 appname app/scheduler.6167:     at WebSocket.emit (events.js:211:7) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver._receiver.onmessage (/app/node_modules/ws/lib/WebSocket.js:141:47) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.dataMessage (/app/node_modules/ws/lib/Receiver.js:389:14) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.getData (/app/node_modules/ws/lib/Receiver.js:330:12) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.startLoop (/app/node_modules/ws/lib/Receiver.js:165:16) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Receiver.add (/app/node_modules/ws/lib/Receiver.js:139:10) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Socket._ultron.on (/app/node_modules/ws/lib/WebSocket.js:138:22) 
Apr 29 09:29:42 appname app/scheduler.6167:     at emitOne (events.js:116:13) 
Apr 29 09:29:42 appname app/scheduler.6167:     at Socket.emit (events.js:211:7) 
Apr 29 09:29:50 appname heroku/scheduler.6167: Process running mem=848M(164.9%) 
Apr 29 09:29:51 appname heroku/scheduler.6167: Error R14 (Memory quota exceeded) 
Apr 29 09:30:10 appname app/scheduler.6167: Error: Navigation Timeout Exceeded: 30000ms exceeded 
Apr 29 09:30:10 appname app/scheduler.6167:     at Promise.then (/app/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21) 
Apr 29 09:30:10 appname app/scheduler.6167:     at <anonymous> 
Apr 29 09:30:12 appname heroku/scheduler.6167: Process running mem=1210M(235.7%) 
Apr 29 09:30:12 appname heroku/scheduler.6167: Error R15 (Memory quota vastly exceeded) 
Apr 29 09:30:12 appname heroku/scheduler.6167: Stopping process with SIGKILL 
Apr 29 09:30:13 appname heroku/scheduler.6167: Process exited with status 137 
Apr 29 09:30:13 appname heroku/scheduler.6167: State changed from up to complete 
```

**Comment by samyun** [comment]
How many alerts do you have set up?

Regards,
Sam Yun

**Comment by rusd1123** [comment]
Currently, I have 13 flights being tracked. I was going to add my remaining booked flights this morning, but noticed the alerts.

**Comment by samyun** [comment]
I see. It seems that I’ll need to do some sort of queuing with these checks.

**Comment by samyun** [comment]
Try this out: https://github.com/samyun/southwest-price-drop-bot/tree/semaphore

**Comment by rusd1123** [comment]
I’ll deploy this evening and update you after it has run a few hours.

**Comment by razzamatazm** [comment]
This is working for me. Granted, I only have 2 alerts.

**Comment by rusd1123** [comment]
Definitely seeing an improvement over the previous process, but still seeing the error. I'll keep watching to see if it repeats consistently.

```
Apr 30 20:59:31 appname app/api: Starting process with command `npm run task:check` by user scheduler@addons.heroku.com 
Apr 30 20:59:46 appname heroku/scheduler.6823: Starting process with command `npm run task:check` 
Apr 30 20:59:47 appname heroku/scheduler.6823: State changed from starting to up 
Apr 30 20:59:48 appname app/scheduler.6823: > southwest-price-drop-bot@3.1.1 task:check /app 
Apr 30 20:59:48 appname app/scheduler.6823: > node --trace-warnings tasks/check.js 
Apr 30 20:59:49 appname app/scheduler.6823: checking 13 flights 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 5 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 4 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 3 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 2 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 1 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: lock has available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: Entered lock, available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: Entered lock, available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: Entered lock, available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: Entered lock, available permits: 0 
Apr 30 20:59:49 appname app/scheduler.6823: Entered lock, available permits: 0 
Apr 30 20:59:57 appname heroku/scheduler.6823: Process running mem=723M(133.4%) 
Apr 30 20:59:57 appname heroku/scheduler.6823: Error R14 (Memory quota exceeded) 
```
